// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/login.proto

package login_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已有的基础消息（保留并补充）
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageHeader) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageHeader) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageHeader) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_proto_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 登录请求（补充完整字段）
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LoginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 登录响应（复用已有结构，补充到 proto 定义中）
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold          int64                  `protobuf:"varint,6,opt,name=gold,proto3" json:"gold,omitempty"`
	Diamond       int64                  `protobuf:"varint,7,opt,name=diamond,proto3" json:"diamond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LoginResponse) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *LoginResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *LoginResponse) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

// 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 包含 user_id 和 session_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_proto_login_proto protoreflect.FileDescriptor

const file_proto_login_proto_rawDesc = "" +
	"\n" +
	"\x11proto/login.proto\x12\vlogin_proto\"\x8e\x01\n" +
	"\rMessageHeader\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\rR\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"U\n" +
	"\vBaseRequest\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.login_proto.MessageHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"|\n" +
	"\fBaseResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.login_proto.MessageHeaderR\x06header\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"|\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xb0\x01\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x06 \x01(\x03R\x04gold\x12\x18\n" +
	"\adiamond\x18\a \x01(\x03R\adiamond\"C\n" +
	"\rLogoutRequest\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.login_proto.MessageHeaderR\x06header2\xdd\x02\n" +
	"\fLoginService\x12>\n" +
	"\x05Login\x12\x19.login_proto.LoginRequest\x1a\x1a.login_proto.LoginResponse\x12A\n" +
	"\bRegister\x12\x19.login_proto.LoginRequest\x1a\x1a.login_proto.LoginResponse\x12?\n" +
	"\x06Logout\x12\x1a.login_proto.LogoutRequest\x1a\x19.login_proto.BaseResponse\x12D\n" +
	"\rValidateToken\x12\x18.login_proto.BaseRequest\x1a\x19.login_proto.BaseResponse\x12C\n" +
	"\fRefreshToken\x12\x18.login_proto.BaseRequest\x1a\x19.login_proto.BaseResponseB*Z(github.com/puoxiu/cogame/pkg/login_protob\x06proto3"

var (
	file_proto_login_proto_rawDescOnce sync.Once
	file_proto_login_proto_rawDescData []byte
)

func file_proto_login_proto_rawDescGZIP() []byte {
	file_proto_login_proto_rawDescOnce.Do(func() {
		file_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)))
	})
	return file_proto_login_proto_rawDescData
}

var file_proto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_login_proto_goTypes = []any{
	(*MessageHeader)(nil), // 0: login_proto.MessageHeader
	(*BaseRequest)(nil),   // 1: login_proto.BaseRequest
	(*BaseResponse)(nil),  // 2: login_proto.BaseResponse
	(*LoginRequest)(nil),  // 3: login_proto.LoginRequest
	(*LoginResponse)(nil), // 4: login_proto.LoginResponse
	(*LogoutRequest)(nil), // 5: login_proto.LogoutRequest
}
var file_proto_login_proto_depIdxs = []int32{
	0, // 0: login_proto.BaseRequest.header:type_name -> login_proto.MessageHeader
	0, // 1: login_proto.BaseResponse.header:type_name -> login_proto.MessageHeader
	0, // 2: login_proto.LogoutRequest.header:type_name -> login_proto.MessageHeader
	3, // 3: login_proto.LoginService.Login:input_type -> login_proto.LoginRequest
	3, // 4: login_proto.LoginService.Register:input_type -> login_proto.LoginRequest
	5, // 5: login_proto.LoginService.Logout:input_type -> login_proto.LogoutRequest
	1, // 6: login_proto.LoginService.ValidateToken:input_type -> login_proto.BaseRequest
	1, // 7: login_proto.LoginService.RefreshToken:input_type -> login_proto.BaseRequest
	4, // 8: login_proto.LoginService.Login:output_type -> login_proto.LoginResponse
	4, // 9: login_proto.LoginService.Register:output_type -> login_proto.LoginResponse
	2, // 10: login_proto.LoginService.Logout:output_type -> login_proto.BaseResponse
	2, // 11: login_proto.LoginService.ValidateToken:output_type -> login_proto.BaseResponse
	2, // 12: login_proto.LoginService.RefreshToken:output_type -> login_proto.BaseResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_login_proto_init() }
func file_proto_login_proto_init() {
	if File_proto_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_login_proto_goTypes,
		DependencyIndexes: file_proto_login_proto_depIdxs,
		MessageInfos:      file_proto_login_proto_msgTypes,
	}.Build()
	File_proto_login_proto = out.File
	file_proto_login_proto_goTypes = nil
	file_proto_login_proto_depIdxs = nil
}
