// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/system.proto

package system_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础请求结构（复用已有定义，若不存在需补充）
type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 透传的请求头（如会话ID、用户ID等）
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     // 业务参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *BaseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 基础响应结构
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 透传的响应头
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`    // 错误码（0为成功）
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`       // 错误信息
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`     // 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponse) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务器信息
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	Load          int32                  `protobuf:"varint,6,opt,name=load,proto3" json:"load,omitempty"`
	UpdateTime    uint32                 `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *NodeInfo) GetLoad() int32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *NodeInfo) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type MemoryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alloc         uint64                 `protobuf:"varint,1,opt,name=alloc,proto3" json:"alloc,omitempty"`                             // 对应 runtime.MemStats.Alloc
	TotalAlloc    uint64                 `protobuf:"varint,2,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"` // 对应 runtime.MemStats.TotalAlloc
	Sys           uint64                 `protobuf:"varint,3,opt,name=sys,proto3" json:"sys,omitempty"`                                 // 对应 runtime.MemStats.Sys
	NumGc         uint32                 `protobuf:"varint,4,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`                // 对应 runtime.MemStats.NumGC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	mi := &file_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryStats) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *MemoryStats) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *MemoryStats) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *MemoryStats) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

// 对应 Go 的 PoolStat 结构体
type PoolStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"` // 对应 PoolStat.Name
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                        // 对应 PoolStat.Size
	Available     int32                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`              // 对应 PoolStat.Available
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`                  // 对应 PoolStat.Created
	Gotten        int64                  `protobuf:"varint,5,opt,name=gotten,proto3" json:"gotten,omitempty"`                    // 对应 PoolStat.Gotten
	Put           int64                  `protobuf:"varint,6,opt,name=put,proto3" json:"put,omitempty"`                          // 对应 PoolStat.Put
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStat) Reset() {
	*x = PoolStat{}
	mi := &file_proto_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStat) ProtoMessage() {}

func (x *PoolStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStat.ProtoReflect.Descriptor instead.
func (*PoolStat) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{4}
}

func (x *PoolStat) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *PoolStat) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PoolStat) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *PoolStat) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PoolStat) GetGotten() int64 {
	if x != nil {
		return x.Gotten
	}
	return 0
}

func (x *PoolStat) GetPut() int64 {
	if x != nil {
		return x.Put
	}
	return 0
}

// 对应 Go 的 ServerStats 结构体
type ServerStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                                     // 对应 ServerStats.NodeID
	NodeType       string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`                                                                               // 对应 ServerStats.NodeType
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                                                                   // 对应 ServerStats.Status
	Uptime         int64                  `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                                                                  // 对应 ServerStats.Uptime（当前代码未赋值，后续可补充）
	Load           int32                  `protobuf:"varint,5,opt,name=load,proto3" json:"load,omitempty"`                                                                                                      // 对应 ServerStats.Load
	Memory         *MemoryStats           `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`                                                                                                   // 对应 ServerStats.Memory
	Goroutines     int32                  `protobuf:"varint,7,opt,name=goroutines,proto3" json:"goroutines,omitempty"`                                                                                          // 对应 ServerStats.Goroutines
	Connections    int32                  `protobuf:"varint,8,opt,name=connections,proto3" json:"connections,omitempty"`                                                                                        // 对应 ServerStats.Connections
	ActorCount     int32                  `protobuf:"varint,9,opt,name=actor_count,json=actorCount,proto3" json:"actor_count,omitempty"`                                                                        // 对应 ServerStats.ActorCount
	RpcConnections int64                  `protobuf:"varint,10,opt,name=rpc_connections,json=rpcConnections,proto3" json:"rpc_connections,omitempty"`                                                           // 对应 ServerStats.RPCConnections
	PoolStats      map[string]*PoolStat   `protobuf:"bytes,11,rep,name=pool_stats,json=poolStats,proto3" json:"pool_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 对应 ServerStats.PoolStats
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerStats) Reset() {
	*x = ServerStats{}
	mi := &file_proto_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStats) ProtoMessage() {}

func (x *ServerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStats.ProtoReflect.Descriptor instead.
func (*ServerStats) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServerStats) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ServerStats) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerStats) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ServerStats) GetLoad() int32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *ServerStats) GetMemory() *MemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ServerStats) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ServerStats) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *ServerStats) GetActorCount() int32 {
	if x != nil {
		return x.ActorCount
	}
	return 0
}

func (x *ServerStats) GetRpcConnections() int64 {
	if x != nil {
		return x.RpcConnections
	}
	return 0
}

func (x *ServerStats) GetPoolStats() map[string]*PoolStat {
	if x != nil {
		return x.PoolStats
	}
	return nil
}

var File_proto_system_proto protoreflect.FileDescriptor

const file_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x12proto/system.proto\x12\fsystem_proto\"9\n" +
	"\vBaseRequest\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"`\n" +
	"\fBaseResponse\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xbb\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\x12\x12\n" +
	"\x04load\x18\x06 \x01(\x05R\x04load\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\rR\n" +
	"updateTime\"m\n" +
	"\vMemoryStats\x12\x14\n" +
	"\x05alloc\x18\x01 \x01(\x04R\x05alloc\x12\x1f\n" +
	"\vtotal_alloc\x18\x02 \x01(\x04R\n" +
	"totalAlloc\x12\x10\n" +
	"\x03sys\x18\x03 \x01(\x04R\x03sys\x12\x15\n" +
	"\x06num_gc\x18\x04 \x01(\rR\x05numGc\"\x9d\x01\n" +
	"\bPoolStat\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x05R\tavailable\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x16\n" +
	"\x06gotten\x18\x05 \x01(\x03R\x06gotten\x12\x10\n" +
	"\x03put\x18\x06 \x01(\x03R\x03put\"\xe5\x03\n" +
	"\vServerStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x05R\x04load\x121\n" +
	"\x06memory\x18\x06 \x01(\v2\x19.system_proto.MemoryStatsR\x06memory\x12\x1e\n" +
	"\n" +
	"goroutines\x18\a \x01(\x05R\n" +
	"goroutines\x12 \n" +
	"\vconnections\x18\b \x01(\x05R\vconnections\x12\x1f\n" +
	"\vactor_count\x18\t \x01(\x05R\n" +
	"actorCount\x12'\n" +
	"\x0frpc_connections\x18\n" +
	" \x01(\x03R\x0erpcConnections\x12G\n" +
	"\n" +
	"pool_stats\x18\v \x03(\v2(.system_proto.ServerStats.PoolStatsEntryR\tpoolStats\x1aT\n" +
	"\x0ePoolStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.system_proto.PoolStatR\x05value:\x028\x012\xfe\x03\n" +
	"\rSystemService\x12F\n" +
	"\rGetServerInfo\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12G\n" +
	"\x0eGetServerStats\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12E\n" +
	"\fReloadConfig\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12C\n" +
	"\n" +
	"UpdateLoad\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12A\n" +
	"\bShutdown\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12F\n" +
	"\rGetActorStats\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponse\x12E\n" +
	"\fGetPoolStats\x12\x19.system_proto.BaseRequest\x1a\x1a.system_proto.BaseResponseB+Z)github.com/puoxiu/cogame/pkg/system_protob\x06proto3"

var (
	file_proto_system_proto_rawDescOnce sync.Once
	file_proto_system_proto_rawDescData []byte
)

func file_proto_system_proto_rawDescGZIP() []byte {
	file_proto_system_proto_rawDescOnce.Do(func() {
		file_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)))
	})
	return file_proto_system_proto_rawDescData
}

var file_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_system_proto_goTypes = []any{
	(*BaseRequest)(nil),  // 0: system_proto.BaseRequest
	(*BaseResponse)(nil), // 1: system_proto.BaseResponse
	(*NodeInfo)(nil),     // 2: system_proto.NodeInfo
	(*MemoryStats)(nil),  // 3: system_proto.MemoryStats
	(*PoolStat)(nil),     // 4: system_proto.PoolStat
	(*ServerStats)(nil),  // 5: system_proto.ServerStats
	nil,                  // 6: system_proto.ServerStats.PoolStatsEntry
}
var file_proto_system_proto_depIdxs = []int32{
	3,  // 0: system_proto.ServerStats.memory:type_name -> system_proto.MemoryStats
	6,  // 1: system_proto.ServerStats.pool_stats:type_name -> system_proto.ServerStats.PoolStatsEntry
	4,  // 2: system_proto.ServerStats.PoolStatsEntry.value:type_name -> system_proto.PoolStat
	0,  // 3: system_proto.SystemService.GetServerInfo:input_type -> system_proto.BaseRequest
	0,  // 4: system_proto.SystemService.GetServerStats:input_type -> system_proto.BaseRequest
	0,  // 5: system_proto.SystemService.ReloadConfig:input_type -> system_proto.BaseRequest
	0,  // 6: system_proto.SystemService.UpdateLoad:input_type -> system_proto.BaseRequest
	0,  // 7: system_proto.SystemService.Shutdown:input_type -> system_proto.BaseRequest
	0,  // 8: system_proto.SystemService.GetActorStats:input_type -> system_proto.BaseRequest
	0,  // 9: system_proto.SystemService.GetPoolStats:input_type -> system_proto.BaseRequest
	1,  // 10: system_proto.SystemService.GetServerInfo:output_type -> system_proto.BaseResponse
	1,  // 11: system_proto.SystemService.GetServerStats:output_type -> system_proto.BaseResponse
	1,  // 12: system_proto.SystemService.ReloadConfig:output_type -> system_proto.BaseResponse
	1,  // 13: system_proto.SystemService.UpdateLoad:output_type -> system_proto.BaseResponse
	1,  // 14: system_proto.SystemService.Shutdown:output_type -> system_proto.BaseResponse
	1,  // 15: system_proto.SystemService.GetActorStats:output_type -> system_proto.BaseResponse
	1,  // 16: system_proto.SystemService.GetPoolStats:output_type -> system_proto.BaseResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_system_proto_init() }
func file_proto_system_proto_init() {
	if File_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_proto_goTypes,
		DependencyIndexes: file_proto_system_proto_depIdxs,
		MessageInfos:      file_proto_system_proto_msgTypes,
	}.Build()
	File_proto_system_proto = out.File
	file_proto_system_proto_goTypes = nil
	file_proto_system_proto_depIdxs = nil
}
