// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/lobby.proto

package lobby_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已有的基础消息（保留并补充）
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageHeader) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageHeader) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageHeader) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_proto_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GamePlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePlayerInfo) Reset() {
	*x = GamePlayerInfo{}
	mi := &file_proto_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayerInfo) ProtoMessage() {}

func (x *GamePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayerInfo.ProtoReflect.Descriptor instead.
func (*GamePlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *GamePlayerInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GamePlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GamePlayerInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GamePlayerInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GamePlayerInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName       string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	GameType       int32                  `protobuf:"varint,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	CurrentPlayers int32                  `protobuf:"varint,4,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	MaxPlayers     int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Status         int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	IsPrivate      bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Owner          *GamePlayerInfo        `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Players        []*GamePlayerInfo      `protobuf:"bytes,9,rep,name=players,proto3" json:"players,omitempty"`
	CreatedTime    uint32                 `protobuf:"varint,10,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *RoomInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *RoomInfo) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoomInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *RoomInfo) GetOwner() *GamePlayerInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RoomInfo) GetPlayers() []*GamePlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfo) GetCreatedTime() uint32 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_proto_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *RoomListResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RoomListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	GameType      int32                  `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_lobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *CreateRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateRoomRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_lobby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_lobby_proto protoreflect.FileDescriptor

const file_proto_lobby_proto_rawDesc = "" +
	"\n" +
	"\x11proto/lobby.proto\x12\x05lobby\"\x8e\x01\n" +
	"\rMessageHeader\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\rR\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"O\n" +
	"\vBaseRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.lobby.MessageHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"v\n" +
	"\fBaseResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.lobby.MessageHeaderR\x06header\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x89\x01\n" +
	"\x0eGamePlayerInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xdf\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\x05R\bgameType\x12'\n" +
	"\x0fcurrent_players\x18\x04 \x01(\x05R\x0ecurrentPlayers\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\x12+\n" +
	"\x05owner\x18\b \x01(\v2\x15.lobby.GamePlayerInfoR\x05owner\x12/\n" +
	"\aplayers\x18\t \x03(\v2\x15.lobby.GamePlayerInfoR\aplayers\x12!\n" +
	"\fcreated_time\x18\n" +
	" \x01(\rR\vcreatedTime\"O\n" +
	"\x10RoomListResponse\x12%\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0f.lobby.RoomInfoR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa9\x01\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\x05R\bgameType\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"F\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xe8\x01\n" +
	"\fLobbyService\x126\n" +
	"\vGetRoomList\x12\x12.lobby.BaseRequest\x1a\x13.lobby.BaseResponse\x125\n" +
	"\n" +
	"CreateRoom\x12\x12.lobby.BaseRequest\x1a\x13.lobby.BaseResponse\x123\n" +
	"\bJoinRoom\x12\x12.lobby.BaseRequest\x1a\x13.lobby.BaseResponse\x124\n" +
	"\tLeaveRoom\x12\x12.lobby.BaseRequest\x1a\x13.lobby.BaseResponseB*Z(github.com/puoxiu/cogame/pkg/lobby_protob\x06proto3"

var (
	file_proto_lobby_proto_rawDescOnce sync.Once
	file_proto_lobby_proto_rawDescData []byte
)

func file_proto_lobby_proto_rawDescGZIP() []byte {
	file_proto_lobby_proto_rawDescOnce.Do(func() {
		file_proto_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)))
	})
	return file_proto_lobby_proto_rawDescData
}

var file_proto_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_lobby_proto_goTypes = []any{
	(*MessageHeader)(nil),     // 0: lobby.MessageHeader
	(*BaseRequest)(nil),       // 1: lobby.BaseRequest
	(*BaseResponse)(nil),      // 2: lobby.BaseResponse
	(*GamePlayerInfo)(nil),    // 3: lobby.GamePlayerInfo
	(*RoomInfo)(nil),          // 4: lobby.RoomInfo
	(*RoomListResponse)(nil),  // 5: lobby.RoomListResponse
	(*CreateRoomRequest)(nil), // 6: lobby.CreateRoomRequest
	(*JoinRoomRequest)(nil),   // 7: lobby.JoinRoomRequest
}
var file_proto_lobby_proto_depIdxs = []int32{
	0, // 0: lobby.BaseRequest.header:type_name -> lobby.MessageHeader
	0, // 1: lobby.BaseResponse.header:type_name -> lobby.MessageHeader
	3, // 2: lobby.RoomInfo.owner:type_name -> lobby.GamePlayerInfo
	3, // 3: lobby.RoomInfo.players:type_name -> lobby.GamePlayerInfo
	4, // 4: lobby.RoomListResponse.rooms:type_name -> lobby.RoomInfo
	1, // 5: lobby.LobbyService.GetRoomList:input_type -> lobby.BaseRequest
	1, // 6: lobby.LobbyService.CreateRoom:input_type -> lobby.BaseRequest
	1, // 7: lobby.LobbyService.JoinRoom:input_type -> lobby.BaseRequest
	1, // 8: lobby.LobbyService.LeaveRoom:input_type -> lobby.BaseRequest
	2, // 9: lobby.LobbyService.GetRoomList:output_type -> lobby.BaseResponse
	2, // 10: lobby.LobbyService.CreateRoom:output_type -> lobby.BaseResponse
	2, // 11: lobby.LobbyService.JoinRoom:output_type -> lobby.BaseResponse
	2, // 12: lobby.LobbyService.LeaveRoom:output_type -> lobby.BaseResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_lobby_proto_init() }
func file_proto_lobby_proto_init() {
	if File_proto_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lobby_proto_goTypes,
		DependencyIndexes: file_proto_lobby_proto_depIdxs,
		MessageInfos:      file_proto_lobby_proto_msgTypes,
	}.Build()
	File_proto_lobby_proto = out.File
	file_proto_lobby_proto_goTypes = nil
	file_proto_lobby_proto_depIdxs = nil
}
