// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/center.proto

package center_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CenterService_GetServiceList_FullMethodName   = "/center_proto.CenterService/GetServiceList"
	CenterService_GetClusterStatus_FullMethodName = "/center_proto.CenterService/GetClusterStatus"
	CenterService_BroadcastMessage_FullMethodName = "/center_proto.CenterService/BroadcastMessage"
	CenterService_ShutdownService_FullMethodName  = "/center_proto.CenterService/ShutdownService"
	CenterService_RestartService_FullMethodName   = "/center_proto.CenterService/RestartService"
)

// CenterServiceClient is the client API for CenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 中心服务定义
type CenterServiceClient interface {
	// 获取服务列表
	GetServiceList(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ServiceListResponse, error)
	// 获取集群状态
	GetClusterStatus(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
	// 广播消息
	BroadcastMessage(ctx context.Context, in *BroadcastMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 关闭服务
	ShutdownService(ctx context.Context, in *ServiceOperationRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 重启服务
	RestartService(ctx context.Context, in *ServiceOperationRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type centerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterServiceClient(cc grpc.ClientConnInterface) CenterServiceClient {
	return &centerServiceClient{cc}
}

func (c *centerServiceClient) GetServiceList(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceListResponse)
	err := c.cc.Invoke(ctx, CenterService_GetServiceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) GetClusterStatus(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, CenterService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) BroadcastMessage(ctx context.Context, in *BroadcastMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, CenterService_BroadcastMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) ShutdownService(ctx context.Context, in *ServiceOperationRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, CenterService_ShutdownService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) RestartService(ctx context.Context, in *ServiceOperationRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, CenterService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterServiceServer is the server API for CenterService service.
// All implementations must embed UnimplementedCenterServiceServer
// for forward compatibility.
//
// 中心服务定义
type CenterServiceServer interface {
	// 获取服务列表
	GetServiceList(context.Context, *BaseRequest) (*ServiceListResponse, error)
	// 获取集群状态
	GetClusterStatus(context.Context, *BaseRequest) (*ClusterStatusResponse, error)
	// 广播消息
	BroadcastMessage(context.Context, *BroadcastMessageRequest) (*CommonResponse, error)
	// 关闭服务
	ShutdownService(context.Context, *ServiceOperationRequest) (*CommonResponse, error)
	// 重启服务
	RestartService(context.Context, *ServiceOperationRequest) (*CommonResponse, error)
	mustEmbedUnimplementedCenterServiceServer()
}

// UnimplementedCenterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCenterServiceServer struct{}

func (UnimplementedCenterServiceServer) GetServiceList(context.Context, *BaseRequest) (*ServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceList not implemented")
}
func (UnimplementedCenterServiceServer) GetClusterStatus(context.Context, *BaseRequest) (*ClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedCenterServiceServer) BroadcastMessage(context.Context, *BroadcastMessageRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedCenterServiceServer) ShutdownService(context.Context, *ServiceOperationRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownService not implemented")
}
func (UnimplementedCenterServiceServer) RestartService(context.Context, *ServiceOperationRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedCenterServiceServer) mustEmbedUnimplementedCenterServiceServer() {}
func (UnimplementedCenterServiceServer) testEmbeddedByValue()                       {}

// UnsafeCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterServiceServer will
// result in compilation errors.
type UnsafeCenterServiceServer interface {
	mustEmbedUnimplementedCenterServiceServer()
}

func RegisterCenterServiceServer(s grpc.ServiceRegistrar, srv CenterServiceServer) {
	// If the following call pancis, it indicates UnimplementedCenterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CenterService_ServiceDesc, srv)
}

func _CenterService_GetServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).GetServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_GetServiceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).GetServiceList(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).GetClusterStatus(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_BroadcastMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).BroadcastMessage(ctx, req.(*BroadcastMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_ShutdownService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).ShutdownService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_ShutdownService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).ShutdownService(ctx, req.(*ServiceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).RestartService(ctx, req.(*ServiceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterService_ServiceDesc is the grpc.ServiceDesc for CenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "center_proto.CenterService",
	HandlerType: (*CenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceList",
			Handler:    _CenterService_GetServiceList_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _CenterService_GetClusterStatus_Handler,
		},
		{
			MethodName: "BroadcastMessage",
			Handler:    _CenterService_BroadcastMessage_Handler,
		},
		{
			MethodName: "ShutdownService",
			Handler:    _CenterService_ShutdownService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _CenterService_RestartService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/center.proto",
}
