// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/center.proto

package center_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已有的基础消息（保留并补充）
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageHeader) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageHeader) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageHeader) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_proto_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_center_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务信息
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`              // 服务ID (对应原NodeID)
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`        // 服务类型 (对应原NodeType)
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                   // 服务地址
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                        // 服务端口
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态 (online/offline)
	LastHeartbeat uint32                 `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // 最后心跳时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_center_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInfo) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceInfo) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetLastHeartbeat() uint32 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// 服务列表响应
type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // 服务列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_proto_center_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceListResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // CPU使用率
	MemoryUsage   float32                `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 内存使用率
	DiskUsage     float32                `protobuf:"fixed32,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`       // 磁盘使用率
	Uptime        uint32                 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                               // 运行时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_center_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{5}
}

func (x *SystemInfo) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemInfo) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemInfo) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemInfo) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

// 集群状态响应
type ClusterStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalServices  int32                  `protobuf:"varint,1,opt,name=total_services,json=totalServices,proto3" json:"total_services,omitempty"`                                                                        // 总服务数
	OnlineServices int32                  `protobuf:"varint,2,opt,name=online_services,json=onlineServices,proto3" json:"online_services,omitempty"`                                                                     // 在线服务数
	ServiceStats   map[string]int32       `protobuf:"bytes,3,rep,name=service_stats,json=serviceStats,proto3" json:"service_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 服务类型统计
	SystemInfo     *SystemInfo            `protobuf:"bytes,4,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`                                                                                  // 系统信息
	Code           int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`                                                                                                               // 状态码 0=成功
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                                                                                          // 消息描述
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_proto_center_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterStatusResponse) GetTotalServices() int32 {
	if x != nil {
		return x.TotalServices
	}
	return 0
}

func (x *ClusterStatusResponse) GetOnlineServices() int32 {
	if x != nil {
		return x.OnlineServices
	}
	return 0
}

func (x *ClusterStatusResponse) GetServiceStats() map[string]int32 {
	if x != nil {
		return x.ServiceStats
	}
	return nil
}

func (x *ClusterStatusResponse) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *ClusterStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClusterStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 广播消息请求
type BroadcastMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`          // 消息类型
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                     // 消息内容
	TargetServices []string               `protobuf:"bytes,3,rep,name=target_services,json=targetServices,proto3" json:"target_services,omitempty"` // 目标服务类型列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastMessageRequest) Reset() {
	*x = BroadcastMessageRequest{}
	mi := &file_proto_center_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessageRequest) ProtoMessage() {}

func (x *BroadcastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessageRequest.ProtoReflect.Descriptor instead.
func (*BroadcastMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BroadcastMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastMessageRequest) GetTargetServices() []string {
	if x != nil {
		return x.TargetServices
	}
	return nil
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码 0=成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // 附加数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_proto_center_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{8}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务操作请求 (关闭/重启)
type ServiceOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`       // 服务ID (可选)
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"` // 服务类型 (可选)
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`                        // 操作类型 (close/restart)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOperationRequest) Reset() {
	*x = ServiceOperationRequest{}
	mi := &file_proto_center_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOperationRequest) ProtoMessage() {}

func (x *ServiceOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOperationRequest.ProtoReflect.Descriptor instead.
func (*ServiceOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_center_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceOperationRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceOperationRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

var File_proto_center_proto protoreflect.FileDescriptor

const file_proto_center_proto_rawDesc = "" +
	"\n" +
	"\x12proto/center.proto\x12\fcenter_proto\"\x8e\x01\n" +
	"\rMessageHeader\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\rR\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"V\n" +
	"\vBaseRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.center_proto.MessageHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"}\n" +
	"\fBaseResponse\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.center_proto.MessageHeaderR\x06header\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xbc\x01\n" +
	"\vServiceInfo\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\rR\rlastHeartbeat\"b\n" +
	"\x13ServiceListResponse\x125\n" +
	"\bservices\x18\x01 \x03(\v2\x19.center_proto.ServiceInfoR\bservices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x83\x01\n" +
	"\n" +
	"SystemInfo\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x02R\tdiskUsage\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\rR\x06uptime\"\xed\x02\n" +
	"\x15ClusterStatusResponse\x12%\n" +
	"\x0etotal_services\x18\x01 \x01(\x05R\rtotalServices\x12'\n" +
	"\x0fonline_services\x18\x02 \x01(\x05R\x0eonlineServices\x12Z\n" +
	"\rservice_stats\x18\x03 \x03(\v25.center_proto.ClusterStatusResponse.ServiceStatsEntryR\fserviceStats\x129\n" +
	"\vsystem_info\x18\x04 \x01(\v2\x18.center_proto.SystemInfoR\n" +
	"systemInfo\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x1a?\n" +
	"\x11ServiceStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x7f\n" +
	"\x17BroadcastMessageRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12'\n" +
	"\x0ftarget_services\x18\x03 \x03(\tR\x0etargetServices\"R\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"y\n" +
	"\x17ServiceOperationRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation2\xbb\x03\n" +
	"\rCenterService\x12N\n" +
	"\x0eGetServiceList\x12\x19.center_proto.BaseRequest\x1a!.center_proto.ServiceListResponse\x12R\n" +
	"\x10GetClusterStatus\x12\x19.center_proto.BaseRequest\x1a#.center_proto.ClusterStatusResponse\x12W\n" +
	"\x10BroadcastMessage\x12%.center_proto.BroadcastMessageRequest\x1a\x1c.center_proto.CommonResponse\x12V\n" +
	"\x0fShutdownService\x12%.center_proto.ServiceOperationRequest\x1a\x1c.center_proto.CommonResponse\x12U\n" +
	"\x0eRestartService\x12%.center_proto.ServiceOperationRequest\x1a\x1c.center_proto.CommonResponseB+Z)github.com/puoxiu/cogame/pkg/center_protob\x06proto3"

var (
	file_proto_center_proto_rawDescOnce sync.Once
	file_proto_center_proto_rawDescData []byte
)

func file_proto_center_proto_rawDescGZIP() []byte {
	file_proto_center_proto_rawDescOnce.Do(func() {
		file_proto_center_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_center_proto_rawDesc), len(file_proto_center_proto_rawDesc)))
	})
	return file_proto_center_proto_rawDescData
}

var file_proto_center_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_center_proto_goTypes = []any{
	(*MessageHeader)(nil),           // 0: center_proto.MessageHeader
	(*BaseRequest)(nil),             // 1: center_proto.BaseRequest
	(*BaseResponse)(nil),            // 2: center_proto.BaseResponse
	(*ServiceInfo)(nil),             // 3: center_proto.ServiceInfo
	(*ServiceListResponse)(nil),     // 4: center_proto.ServiceListResponse
	(*SystemInfo)(nil),              // 5: center_proto.SystemInfo
	(*ClusterStatusResponse)(nil),   // 6: center_proto.ClusterStatusResponse
	(*BroadcastMessageRequest)(nil), // 7: center_proto.BroadcastMessageRequest
	(*CommonResponse)(nil),          // 8: center_proto.CommonResponse
	(*ServiceOperationRequest)(nil), // 9: center_proto.ServiceOperationRequest
	nil,                             // 10: center_proto.ClusterStatusResponse.ServiceStatsEntry
}
var file_proto_center_proto_depIdxs = []int32{
	0,  // 0: center_proto.BaseRequest.header:type_name -> center_proto.MessageHeader
	0,  // 1: center_proto.BaseResponse.header:type_name -> center_proto.MessageHeader
	3,  // 2: center_proto.ServiceListResponse.services:type_name -> center_proto.ServiceInfo
	10, // 3: center_proto.ClusterStatusResponse.service_stats:type_name -> center_proto.ClusterStatusResponse.ServiceStatsEntry
	5,  // 4: center_proto.ClusterStatusResponse.system_info:type_name -> center_proto.SystemInfo
	1,  // 5: center_proto.CenterService.GetServiceList:input_type -> center_proto.BaseRequest
	1,  // 6: center_proto.CenterService.GetClusterStatus:input_type -> center_proto.BaseRequest
	7,  // 7: center_proto.CenterService.BroadcastMessage:input_type -> center_proto.BroadcastMessageRequest
	9,  // 8: center_proto.CenterService.ShutdownService:input_type -> center_proto.ServiceOperationRequest
	9,  // 9: center_proto.CenterService.RestartService:input_type -> center_proto.ServiceOperationRequest
	4,  // 10: center_proto.CenterService.GetServiceList:output_type -> center_proto.ServiceListResponse
	6,  // 11: center_proto.CenterService.GetClusterStatus:output_type -> center_proto.ClusterStatusResponse
	8,  // 12: center_proto.CenterService.BroadcastMessage:output_type -> center_proto.CommonResponse
	8,  // 13: center_proto.CenterService.ShutdownService:output_type -> center_proto.CommonResponse
	8,  // 14: center_proto.CenterService.RestartService:output_type -> center_proto.CommonResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_center_proto_init() }
func file_proto_center_proto_init() {
	if File_proto_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_center_proto_rawDesc), len(file_proto_center_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_center_proto_goTypes,
		DependencyIndexes: file_proto_center_proto_depIdxs,
		MessageInfos:      file_proto_center_proto_msgTypes,
	}.Build()
	File_proto_center_proto = out.File
	file_proto_center_proto_goTypes = nil
	file_proto_center_proto_depIdxs = nil
}
